coverage:
  precision: 2
  round: down
  range: '95...100'
  status:
    patch: off # Disable codecov patches because only the global project coverage matters
    project:
      default:
        target: 95%
