/stripe/accepted:
  post:
    summary: Webhook appelé par Stripe permettant de confirmer un paiement
    description: Webhook appelé par Stripe une fois qu'un paiement est confirmé. L'événement attendu est 'checkout.session.completed', regardez la documentation Stripe pour plus d'informations.
    tags:
      - Stripe
    responses:
      200:
        description: Le panier a été marqué comme payé.
        content:
          application/json:
            schema:
              type: object
              properties:
                api:
                  type: string
                  example: 'ok'
      404:
        $ref: '#/components/responses/404CartNotFound'

/stripe/expired:
  post:
    summary: Webhook appelé par Stripe permettant de signaler qu'un paiement a expiré
    description: Webhook appelé par Stripe une fois qu'un paiement a expiré (sa création a eu lieu il y a plus d'une heure et n'a pas été payé).
    tags:
      - Stripe
    responses:
      200:
        description: L'information a bien été prise en compte.
        content:
          application/json:
            schema:
              type: object
              properties:
                api:
                  type: string
                  example: 'ok'
      403:
        $ref: '#/components/responses/404CartNotFound'
